export const brand = {
  primary: '#6C5CE7',
  primaryLight: '#A29BFE',
  primaryDark: '#4A3DB5',
  secondary: '#00CEC9',
  secondaryLight: '#81ECEC',
  accent: '#FD79A8',
  accentLight: '#FDCB6E',
  gold: '#FDCB6E',
  goldDark: '#E17055',
  success: '#00B894',
  warning: '#FDCB6E',
  error: '#FF7675',
  info: '#74B9FF',
};

export const gradients = {
  primary: ['#6C5CE7', '#A29BFE'] as const,
  secondary: ['#00CEC9', '#81ECEC'] as const,
  accent: ['#FD79A8', '#FDCB6E'] as const,
  gold: ['#FDCB6E', '#E17055'] as const,
  dark: ['#2D3436', '#636E72'] as const,
  card: ['#FFFFFF', '#F8F9FA'] as const,
  cardDark: ['#2D3436', '#1E272E'] as const,
  xpBar: ['#6C5CE7', '#A29BFE'] as const,
  tokenBar: ['#FDCB6E', '#E17055'] as const,
};

const Colors = {
  light: {
    text: '#2D3436',
    textSecondary: '#636E72',
    textMuted: '#B2BEC3',
    background: '#F8F9FA',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    border: '#E9ECEF',
    borderLight: '#F1F3F5',
    tint: brand.primary,
    tabIconDefault: '#B2BEC3',
    tabIconSelected: brand.primary,
    tabBarBackground: '#FFFFFF',
    headerBackground: '#FFFFFF',
    cardBackground: '#FFFFFF',
    inputBackground: '#F1F3F5',
    shadow: 'rgba(0, 0, 0, 0.08)',
    overlay: 'rgba(0, 0, 0, 0.5)',
    ...brand,
  },
  dark: {
    text: '#F8F9FA',
    textSecondary: '#B2BEC3',
    textMuted: '#636E72',
    background: '#1E272E',
    surface: '#2D3436',
    surfaceElevated: '#3D4A4F',
    border: '#3D4A4F',
    borderLight: '#2D3436',
    tint: brand.primaryLight,
    tabIconDefault: '#636E72',
    tabIconSelected: brand.primaryLight,
    tabBarBackground: '#2D3436',
    headerBackground: '#2D3436',
    cardBackground: '#2D3436',
    inputBackground: '#3D4A4F',
    shadow: 'rgba(0, 0, 0, 0.3)',
    overlay: 'rgba(0, 0, 0, 0.7)',
    ...brand,
  },
};

export default Colors;
